[package]
name    = "fadroma-terra-base"
version = "0.1.0"
authors = ["Adam A. <adam@hack.bg>"]
edition = "2018"

[lib]
name = "fadroma_terra_base"
path = "terra_base.rs"

[dependencies]
cosmwasm-std     = { version = "0.15.0" }
cosmwasm-storage = { version = "0.15.0" }
cw-storage-plus  = { version = "0.7.0", features = ["iterator"] }
cw20             = { version = "0.7.0" }
schemars         = "0.8.3"
serde            = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror        = { version = "1.0.24" }

[features]
backtraces = [ "cosmwasm-std/backtraces" ]

