[package]
name = "fadroma-scrt-contract"
version = "0.1.0"
authors = ["Adam Avramov <adam@hack.bg>"]
edition = "2018"

[lib]
path = "contract.rs"
doctest = false # ???

[dependencies]
fadroma-scrt-base = { optional = true, path = "../base" }
fadroma-scrt-icc  = { optional = true, path = "../icc" }

[features]
browser = []
harness = ["fadroma-scrt-base", "fadroma-scrt-icc"]
