# This file is not called Cargo.toml in order to allow
# using Fadroma as a Git submodule in repos that are
# already workspaces (because Cargo doesn't support
# nested workspaces). See `package.lock` for usage info.

[workspace]
members = [
  "crates/auth/",
  "crates/bind-js/",
  "crates/composability/",
  "crates/composable-snip20/",
  "crates/declare-contract/",
  "crates/derive-contract/",
  "crates/killswitch/",
  "crates/math/",
  "crates/require-admin/",
  "crates/scrt/",
  "crates/snip20-api/",
  "crates/storage/",
  "crates/terra/",
]

[profile.release]
opt-level        = 3
debug            = false
rpath            = false
lto              = true
debug-assertions = false
codegen-units    = 1
panic            = 'abort'
incremental      = false
overflow-checks  = true
