[package]
name    = "fadroma-composability"
version = "0.1.0"
edition = "2018"
authors = ["Adam A. <adam@hack.bg>"]

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
fadroma-platform-scrt = { path = "../fadroma-platform-scrt" }
