[package]
name = "fadroma-scrt"
version = "0.1.0"
authors = ["Adam A. <adam@hack.bg>"]
edition = "2018"

[lib]
name = "fadroma"
path = "scrt_core.rs"

[dependencies]
secret-toolkit   = { optional = true, git = "https://github.com/hackbg/secret-toolkit", rev = "9a33d7b" }

fadroma-scrt-base        = { optional = true, path = "../base" }
fadroma-scrt-addr        = { optional = true, path = "../addr" }
fadroma-scrt-icc         = { optional = true, path = "../icc" }
fadroma-scrt-contract    = { optional = true, path = "../contract" }
fadroma-scrt-migrate     = { optional = true, path = "../migrate" }
fadroma-scrt-storage     = { optional = true, path = "../storage" }
fadroma-scrt-snip20-api  = { optional = true, path = "../snip20/api" }
fadroma-scrt-utils       = { optional = true, path = "../utils" }

composable-auth   = { optional = true, path = "../auth" }

composable-admin  = { optional = true, path = "../admin/composable-admin" }
require-admin     = { optional = true, path = "../admin/require-admin" }

#composable-snip20   = { optional = true, path = "../scrt-snip20" } # !!! circular !!!

[features]
scrt            = ["fadroma-scrt-base"]
scrt-addr       = ["scrt", "fadroma-scrt-addr"]
scrt-admin      = ["scrt", "fadroma-scrt-utils", "composable-admin", "require-admin"]
scrt-contract   = ["scrt", "fadroma-scrt-contract"]
scrt-icc        = ["scrt", "fadroma-scrt-icc"]
scrt-migrate    = ["scrt", "fadroma-scrt-migrate"]
scrt-snip20-api = ["scrt", "fadroma-scrt-snip20-api"]
scrt-storage    = ["scrt", "fadroma-scrt-storage"]
scrt-utils      = ["scrt", "fadroma-scrt-utils"]
scrt-vk         = ["scrt", "fadroma-scrt-utils", "composable-auth"]

browser = ["fadroma-scrt-contract/browser", "fadroma-scrt-base/backtraces" ]
