[package]
name = "fadroma-scrt-icc"
version = "0.1.0"
authors = ["Asparuh Kamenov <aakamenov@hack.bg>",
           "Adam Avramov <adam@hack.bg>"]
edition = "2018"

[lib]
path = "scrt_icc.rs"
doctest = false # ???

[dependencies]
schemars = "0.7"
serde    = { version = "1.0.103", default-features = false, features = ["derive"] }

fadroma-scrt-base = { path = "../base" }
fadroma-scrt-addr = { path = "../addr" }
