[package]
name    = "fadroma-scrt-harness"
version = "0.1.0"
edition = "2018"
authors = ["Adam A. <adam@hack.bg>"]

[lib]
name = "fadroma_scrt_harness"
path = "harness.rs"

[dependencies]
fadroma-scrt-base     = { path = "../scrt" }
fadroma-scrt-callback = { path = "../scrt-callback" }

serde = { version = "1.0.103", default-features = false, features = ["derive"] }
