[package]
name    = "fadroma-scrt-snip20-api"
version = "0.1.0"
edition = "2018"
authors = ["Adam A. <adam@hack.bg>"]

[lib]
name = "fadroma_scrt_snip20_api"
path = "scrt_snip20_api.rs"

[dependencies]
fadroma-scrt-base = { path = "../../base" }
fadroma-scrt-icc  = { path = "../../icc" }
