[package]
name = "composable-auth"
version = "0.1.0"
authors = ["Asparuh Kamenov <asparuh@hack.bg>"]
edition = "2018"

[lib]
path = "scrt_icc.rs"
doctest = false

[dependencies]
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

fadroma-scrt-base  = { path = "../base" }
fadroma-scrt-utils = { path = "../utils" }
