name: Run JS tests
on: [push, pull_request]
jobs:

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: actions/setup-node@v1
        with: { node-version: 14 }
      - name: test js modules
        run: yarn && yarn test-ts
