name: Run JS tests
on: [push, pull_request]
jobs:

  js:
    runs-on: ubuntu-latest
    steps:
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3

      - name: Create minimal project
        run: |
          ls -al
          echo '{}' > package.json
          pnpm add github:hackbg/ganesha
          ls -al node_modules
          pnpm i
          node_modules/.bin/ganesha-node
