name: Run tests
on: [push, pull_request]
jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd example && cargo test

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 16 }
      - run: node --version
      - run: npm install -g npm
      - run: npm --version
      - run: npm install
      - run: npm test
